language: node_js
node_js:
- '0.10'
git:
  depth: 10
services:
- couchdb
addons:
  sauce_connect: true
before_install:
- HOST="http://127.0.0.1:5984"
- curl -X PUT $HOST/_config/admins/tester -d '"testerpass"'
before_script:
- npm install -g grunt-cli
- grunt dev &
script:
- grunt nightwatch_saucelabs
env:
  global:
    secure: ReVyiiHg5+Q7G3270JmhyUdYzMmQKAKPIX7Wzo3dBjlv5IU0sGZwoI0I1DeDrTYb+6SMScV70/Ac4eI75kto7xPIIky1JJGSB0FlvEWlDEgrt6WejyWJUmmnEgBZ85R9KfBtLMlnbEI/1fNaevzQg9I9yCdlasPSezHsGzEOpdc=
