language: node_js
node_js:
- '0.10'
git:
  depth: 10
services:
- couchdb
addons:
  sauce_connect: true
before_install:
- HOST="http://127.0.0.1:5984"
- curl -X PUT $HOST/_config/admins/tester -d '"testerpass"'
before_script:
- npm install -g grunt-cli
- grunt dev &
- cat test/nightwatch_tests/nightwatch.json
script:
- grunt nightwatch_saucelabs
env:
  global:
  - secure: tFMWHR1UnXuIwFpJUSOtnUYMMZCmfr9UtlWj1waKNCOoB8QUEpgwddKzhXTP9BxBEpeCctcnqUz06L/ntvEX9rymJwifyy2YEel9knMdwFnscKQ963kUBBnjNFQRRo4Ea9lPdErJEAdSHYRlPUJIe7j2fanzsinneGNNW0jC7Hs=
  - secure: sroHBeClUtMOEpqr6Lnedcy1AnKlYL7lW9S27h+VatTJDjzehCpsIVV7A4LuoIGUnMv+Jwn/lH9CukL99iztKXPImd6HYA2p/75pEgXsfSoyO93EU76FcGitVJuTc957pQw/4aOPbJpxvObJbT+D3xXdxNVkpekumrf4gvCfsDk=
